# Generated by Django 3.0.3 on 2020-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
