# Generated by Django 3.0.3 on 2020-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200626_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='files',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='table',
            name='files2',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='TableFile',
        ),
    ]
