# Generated by Django 3.0.3 on 2020-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200626_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='files2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
