# Generated by Django 3.0.3 on 2020-06-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_table_files2'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='files2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
