# Generated by Django 3.0.3 on 2020-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Portfolio',
        ),
    ]
