# Generated by Django 3.0.3 on 2020-06-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20200610_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='a_image',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='post',
            new_name='a_post',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='a_title',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='image',
            new_name='s_image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='post',
            new_name='s_post',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='title',
            new_name='s_title',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='t_image',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='post',
            new_name='t_post',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='t_title',
        ),
    ]
