# Generated by Django 3.0.3 on 2020-06-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20200618_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='p_image',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='post',
            new_name='p_post',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='p_title',
        ),
    ]
