# Generated by Django 3.0.3 on 2020-06-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20200619_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='s_image',
        ),
    ]
